{{- if and .Values.kafka .Values.kafka.security .Values.kafka.security.enabled (not .Values.kafka.security.caSecretName) .Values.kafka.security.certData }}
apiVersion: v1
kind: Secret
metadata:
  name: alertas-kafka-ca-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.kafka.security.certData | b64enc }}
---
{{- end }}
